// Transcript Export Utility for the AI Courtroom Debate Simulator

class TranscriptExporter {
  static generateMarkdown(topic, model, leftPersona, rightPersona, roundsData, winnerId, leftAvg, rightAvg, fallacies = []) {
    let md = `# ⚖️ AI Courtroom Debate Simulator Recap\n\n`;
    
    md += `## 🏛️ Trial Details\n`;
    md += `- **Topic:** ${topic}\n`;
    md += `- **Date:** ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}\n`;
    md += `- **Model Utilized:** \`${model}\`\n`;
    md += `- **Total Rounds:** ${roundsData.length}\n\n`;

    md += `## 👥 Counsel Profiles\n`;
    md += `- **Plaintiff:** ${leftPersona.name}\n  *Ideology: ${leftPersona.description}*\n`;
    md += `- **Defendant:** ${rightPersona.name}\n  *Ideology: ${rightPersona.description}*\n\n`;

    md += `## 🏆 Final Judgment\n`;
    const winnerName = winnerId === "left" ? leftPersona.name : (winnerId === "right" ? rightPersona.name : "Draw Decision");
    md += `- **Verdict:** **${winnerName}** declared the winner.\n`;
    md += `- **Plaintiff Avg Score:** ${leftAvg} / 10.0\n`;
    md += `- **Defendant Avg Score:** ${rightAvg} / 10.0\n\n`;

    md += `--- \n\n`;
    md += `## 📜 Case Transcript\n\n`;

    roundsData.forEach((r, idx) => {
      md += `### 📍 Round ${idx + 1}\n\n`;
      
      // Plaintiff Speech
      md += `#### 🗣️ Plaintiff: ${leftPersona.name}\n`;
      md += `> ${r.leftText.trim().replace(/\n/g, '\n> ')}\n\n`;

      // Defendant Speech
      md += `#### 🗣️ Defendant: ${rightPersona.name}\n`;
      md += `> ${r.rightText.trim().replace(/\n/g, '\n> ')}\n\n`;

      // Judge Review
      if (r.judgeScore) {
        md += `#### ⚖️ Judicial Review (Round ${idx + 1})\n`;
        md += `- **Plaintiff Scores:** Logic: ${r.judgeScore.left.logic}/10 | Evidence: ${r.judgeScore.left.evidence}/10 | Persuasion: ${r.judgeScore.left.persuasion}/10 (Total: ${r.judgeScore.left.total}/10)\n`;
        md += `- **Defendant Scores:** Logic: ${r.judgeScore.right.logic}/10 | Evidence: ${r.judgeScore.right.evidence}/10 | Persuasion: ${r.judgeScore.right.persuasion}/10 (Total: ${r.judgeScore.right.total}/10)\n`;
        md += `- **Justice AI Opinion:** *"${r.judgeScore.commentary}"*\n\n`;
      }
      md += `---\n\n`;
    });

    // Fallacy Audit Section
    if (fallacies && fallacies.length > 0) {
      md += `## 🔍 Post-Debate Fallacy Audit Report\n\n`;
      md += `| Round | Speaker | Fallacy Type | Flagged Phrase | Analysis |\n`;
      md += `| :---: | :--- | :--- | :--- | :--- |\n`;
      
      fallacies.forEach(f => {
        const speakerName = f.side === "left" ? leftPersona.name : rightPersona.name;
        const capitalizedType = f.type.charAt(0).toUpperCase() + f.type.slice(1);
        md += `| ${f.round} | ${speakerName} | **${capitalizedType}** | *"${f.quote}"* | ${f.explanation} |\n`;
      });
      md += `\n`;
    } else if (fallacies) {
      md += `## 🔍 Post-Debate Fallacy Audit Report\n`;
      md += `*No fallacies were flagged in this session. Exceptional logical consistency demonstrated by both parties.*\n\n`;
    }

    md += `*Recap generated by the AI Courtroom Debate Simulator. Built on Gemini AI.*`;

    return md;
  }

  static downloadMarkdown(topic, model, leftPersona, rightPersona, roundsData, winnerId, leftAvg, rightAvg, fallacies = []) {
    const mdContent = this.generateMarkdown(topic, model, leftPersona, rightPersona, roundsData, winnerId, leftAvg, rightAvg, fallacies);
    
    const blob = new Blob([mdContent], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    
    const cleanTopic = topic.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    const filename = `debate-recap-${cleanTopic}-${Date.now()}.md`;
    
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", filename);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}
